import 'package:flutter/widgets.dart';

/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/Icons.ttf
///
///
///

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'Icons';

  static const IconData potok = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData inbox = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData like = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData back = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData profileHeartPublic =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData profileGrid = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData profileHeartPrivate =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData profileHeartFilled =
      IconData(0xe80b, fontFamily: _kFontFam);
}

class TikTokIcons {
  TikTokIcons._();

  static const _kFontFam = 'TikTokIcons';

  static const IconData chat_bubble =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData create = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData messages =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData reply = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80f, fontFamily: _kFontFam);
}
